### ISSUE TITLE
Redirects back to localhost

### ISSUE THREAD

**Issue by sidmfund** [blackbaud/sky-api-auth-tutorial#11]
As soon as I hit authorize button the app redirects back to localhost:5000 and nothing happens. @Blackbaud-ChristopherRodgers

**Comment by lucasfoster12** [comment]
I have the same issue. The redirect has the following response header: /#?error=Response%20Error:%20400%20Bad%20Request.

**Comment by lucasfoster12** [comment]
@sidmfund 
I was able to get the auth flow working by adding the following to config in auth.js:
`options: { authorizationMethod: 'body' }`

![image](https://github.com/user-attachments/assets/1f3363e9-61d5-4f16-9c3c-6cd61517acbd)

**Comment by Blackbaud-ChristopherRodgers** [comment]
This has been resolved in #14.

**Comment by Blackbaud-ChristopherRodgers** [comment]
This has been resolved in #14 .
