### ISSUE TITLE
jScript runtime error 800A138F Object expected

### ISSUE THREAD

**Issue by fetila** [blackbaud/sky-api-auth-tutorial#6]
Hi,

When I run index.js I get this error on fs = require('fs'); error says Object Expected, code 800A138F

Does someone know why?

![error](https://user-images.githubusercontent.com/49924979/56758488-9dd99000-674b-11e9-8dca-cee7e9010003.PNG)

**Comment by Blackbaud-AdamHickey** [comment]
How are you running index.js?

Make sure you have started your server with "npm start", then you can navigate to http://localhost:5000/.

**Comment by fetila** [comment]
Yes, that was the problem, it is working now. thank you!
