### ISSUE TITLE
This page can't be displayed error

### ISSUE THREAD

**Issue by fetila** [blackbaud/sky-api-auth-tutorial#7]
Hello,

So I followed the steps in the tutorial using this script and I can login and then I click authorize and then is says:
This page can't be displayed    
localhost sent an invalid response.  
ERR_SSL_PROTOCOL_ERROR

Has anyone encountered this issue? Do I need some kind of certificate? What am I missing? 

Thank you!

**Comment by Blackbaud-MichaelCollier** [comment]
Hi Fetila,

If you don't have a certificate installed and you're trying to run with https enabled you'll run into SSL errors.  The other option is to remove https from your applications redirect URI and just test with http.  Make sure you update your settings in your .env file as well.

I'd also recommend reviewing and joining the Blackbaud Community.  There's a lot of developers helping developers here with open forums.  https://community.blackbaud.com/developer

Thanks!
Michael
